apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-ingress
  labels:
    app: ingress
spec:                          
  ingressClassName: nginx  
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: app-service
            port: 
              number: 80
